- hosts: servers
  become: false
  gather_facts: false

  vars:
    PROJECT_ROOT: "/home/{{ ansible_user }}/task2"
    WAR_SOURCE: "/home/{{ ansible_user }}/task2/builds/petclinic.war"
    TOMCAT_HOME: "/home/{{ ansible_user }}/tomcat"
    WEBAPPS: "{{ TOMCAT_HOME }}/webapps"
    WAR_DEST: "{{ WEBAPPS }}/petclinic.war"

  tasks:

    # ---------------------------------------------------------
    # 1) Copy ServletInitializer template
    # ---------------------------------------------------------
   # - name: Copy ServletInitializer template
    #  copy:
     #   src: templates/ServletInitializer.java
      #  dest: "/home/{{ ansible_user }}/templates/ServletInitializer.java"
       # mode: '0644'

    # ---------------------------------------------------------
    # 2) Build PetClinic WAR
    # ---------------------------------------------------------
    - name: Build PetClinic WAR
      shell: "/bin/bash scripts/build_petclinic.sh"
      args:
        chdir: "{{ PROJECT_ROOT }}"
      environment:
        JAVA_HOME: "/home/{{ ansible_user }}/java/jdk-25.0.1"
        PATH: "/home/{{ ansible_user }}/java/jdk-25.0.1/bin:{{ ansible_env.PATH }}"
        ANSIBLE_USER: "{{ ansible_user }}"

    # ---------------------------------------------------------
    # 3) Stop Tomcat before deploying new WAR
    # ---------------------------------------------------------
    - name: Stop Tomcat
      shell: |
        {{ TOMCAT_HOME }}/bin/shutdown.sh || true
        pkill -f '{{ TOMCAT_HOME }}' || true
      ignore_errors: true

    - name: Wait for shutdown
      pause:
        seconds: 3

    # ---------------------------------------------------------
    # 4) Clean old deployment
    # ---------------------------------------------------------
    - name: Remove old exploded application
      file:
        path: "{{ WEBAPPS }}/petclinic"
        state: absent

    - name: Remove old WAR file
      file:
        path: "{{ WAR_DEST }}"
        state: absent

    # ---------------------------------------------------------
    # 5) Copy new WAR
    # ---------------------------------------------------------
    - name: Copy new WAR
      copy:
        src: "{{ WAR_SOURCE }}"
        dest: "{{ WAR_DEST }}"
        mode: "0644"

    # ---------------------------------------------------------
    # 6) Start Tomcat (DETACHED MODE)
    # ---------------------------------------------------------
    - name: Start Tomcat (detached, using Java 25 from setenv.sh)
      shell: |
        /bin/bash -l -c "nohup {{ TOMCAT_HOME }}/bin/startup.sh >/dev/null 2>&1 &"

    - name: Wait for Tomcat to initialize
      pause:
        seconds: 6

    # ---------------------------------------------------------
    # 7) Sanity Check
    # ---------------------------------------------------------
    - name: Wait until PetClinic responds
      uri:
        url: "http://127.0.0.1:9090/petclinic/"
        status_code: 200
        return_content: yes
      register: sanity
      retries: 20
      delay: 5
      until: sanity.status == 200

    - debug:
        var: sanity.status
